# Select what we should cache.
cache:
  paths:
  - vendor/

services:
- mysql:5.7

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/).
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql
  WP_VERSION: latest
  WP_MULTISITE: "0"

before_script:
# Install git, the php image doesn't have installed.
- apt-get install git -yqq

# Install the required packages for the running CI tests.
- apt-get -yqqf install zip unzip wget subversion mysql-client libmcrypt-dev --fix-missing

# Install ssh-agent for deployment.
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

# Install mysql driver
- docker-php-ext-install mysqli pdo_mysql mbstring

# PHP extensions
- docker-php-ext-enable mysqli pdo_mysql mbstring

# Install composer.
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies.
- php composer.phar install

# Setup the test suite.
- bash bin/install-wp-tests.sh $MYSQL_DATABASE root $MYSQL_ROOT_PASSWORD mysql $WP_VERSION

# We test PHP5.6.
test:php5.6:
  image: php:5.6
  stage: test
  script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove --colors=never

# We test PHP5.6 with multisite.
test:php5.6:multisite:
  variables:
    WP_VERSION: latest
    WP_MULTISITE: "1"
  image: php:5.6
  stage: test
  script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove --colors=never

# Test on PHP 7.1.
test:php71:
  image: php:7.1.3
  stage: test
  script:
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug-2.5.5
  - docker-php-ext-enable xdebug
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors=never

# Test on PHP 7.2.
test:php72:
  image: php:7.2.0
  stage: test
  script:
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug-2.6.1
  - docker-php-ext-enable xdebug
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors=never

# We test PHP7 with multisite.
test:php7:multisite:
  variables:
    WP_VERSION: latest
    WP_MULTISITE: "1"
  image: php:7.1
  stage: test
  script:
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug-2.5.5
  - docker-php-ext-enable xdebug
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clove --colors=never